### ISSUE TITLE
창고 관리자는 로케이션의 비어있는 공간을 조회할 수 있다.

### ISSUE THREAD

**Issue by subkka** [ssg-java3-240304/wms-Ten-SaintLaurent#22]
## 🌈 Success criteria
1. Locate 테이블에서 개수가 null인 로케이트 ID와 lpn_code를 조회한다.

## 👷To-do
- [x] Controller 클래스에 searchLpn() 메소드 생성
- [x] Service 클래스에 searchLpn() 메소드 생성
- [x] LocateMapper 인터페이스 생성
- [x] LocateDto 클래스 생성
- [x] locate-mapper.xml 생성
- [x] locate-mapper.xml에 쿼리문 생성
- [x] LocateMapperTest 생성해서 테스트 진행

**Comment by subkka** [comment]
Feat: 조회 sql 생성 #17
