### ISSUE TITLE
창고관리자는 로케이션이 비어있으면 입고를 승인할 수 있다.

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/wms-Ten-SaintLaurent#34]
## 🌈 Success criteria
1. 유통업체가 제작 요청을 하면 창고 관리자는 창고의 빈공간이 있는지 확인합니다.
2. Locate_tb의 LOCATE_ITEM_CNT가 0인 로케이트를 COUNT합니다.
    2-1. COUNT가 1 이상이면, 빈 공간이 있다고 출력합니다.
        2-1-1. 입고 검수를 진행합니다.
    2-2. COUNT가 0이면, 빈 공간이 없다고 출력합니다.
        2-2-1. 유통업체에게 입고 거부 알림을 보냅니다.
    
## 👷To-do
- [ ]  InboundController클래스에 findEmptyLocate() 메소드 생성
- [ ]  InboundService클래스에 findEmptyLocate() 메소드 생성
- [ ]  InboundMapper 인터페이스 생성
- [ ]  Inbound-mapper.xml에 findEmptyLocate 쿼리문 생성
