### ISSUE TITLE
창고관리자는 제조업체의 지역이 창고와 동일하면 입고를 승인할 수 있다.

### ISSUE THREAD

**Issue by jyna120** [ssg-java3-240304/wms-Ten-SaintLaurent#35]
## 🌈 Success criteria
1. 유통업체가 입고요청을 하면 창고 관리자는 창고의 지역과 제조업체의 지역이 일치한지 확인합니다.
2-1. 지역이 일치하면, 빈 공간이 있는지 확인합니다.
2-2. 지역이 일치하지 않으면, 입고를 거부합니다.

## 👷To-do
- [ ]  InboundController클래스에 searchLocEqaul() 메소드 생성
- [ ]  InboundService클래스에 serarchLocEqual() 메소드 생성
- [ ]  InboundMapper 인터페이스 생성
- [ ]  Inbound-mapper.xml에 serarchLocEqual()쿼리문 생성
