### ISSUE TITLE
창고 관리자는 화장품을 폐기할 수 있습니다.

### ISSUE THREAD

**Issue by subkka** [ssg-java3-240304/wms-Ten-SaintLaurent#43]
## 🌈 Success criteria
1. 화장품의 불량 여부를 조회한다.
2. 화장품의 유통기한이 임박한 제품을 조회한다.
3. 해당 제품들의 목록을 폐기 테이블에 작성한다.
4. 화장품 상세 테이블에서 불량 화장품들을 폐기한다.

## 👷To-do
- [x] Controller 클래스에 deleteItem() 메소드 생성
- [x] Service 클래스에 deleteItem() 메소드 생성
- [x] SupervisionMapper 인터페이스에 searchDefItem() 메소드 생성
- [x] SupervisionMapper 인터페이스에 insertGbgDetail() 메소드 생성
- [x] SupervisionMapper 인터페이스에 deleteDetailItem() 메소드 생성
- [x] GbgDetailDto 클래스 생성
- [x] supervision-mapper.xml에 searchDefItem() sql문 생성
- [x] supervision-mapper.xml에 insertGbgDetail() sql문 생성
- [x] supervision-mapper.xml에 deleteItem() sql문 생성
- [ ] SupervisionMapperTest에서 테스트 진행
